### ISSUE TITLE
Write system architecture description (#6)

### ISSUE THREAD

**Issue by flaviut** [gsu-swe-s2019-group-1/project#1]
Edit https://github.com/gsu-swe-s2019-group-1/project/blob/master/assignments/asn1/system_requirements.md to include this information.

----------------
# System Requirements

Describe at a very high level the system's architecture, identifying the
components/modules that will interact.

- Use context model
- See Ch5: Section 5.1 and Figures 5.1

**Comment by apetros1** [comment]
[Context Model.docx](https://github.com/gsu-swe-s2019-group-1/project/files/2815939/Context.Model.docx)

**Comment by flaviut** [comment]
I've uploaded into the git repo at https://github.com/gsu-swe-s2019-group-1/project/blob/master/assignments/asn1/context_model.docx.

The advantage of keeping files in git is that it is easy to track changes made by multiple people, and that is not possible when files are uploaded as attachments to issues.

Also, when you finish something, go ahead and click the close button to indicate that you've done it!
