### ISSUE TITLE
Write Use Case Requirements

### ISSUE THREAD

**Issue by apetros1** [gsu-swe-s2019-group-1/project#10]
In this section you will clearly mention the requirements for each use case you have. Therefore, if you have 12 use cases you should have 12 requirements in this section. The requirements must be written in the following format:

Requirement number:
Use Case number:
Introduction:
Inputs:
Requirements Description:
Outputs:

Refer page 124 Figure 4.13 : Read 4.1, 4.1.1, 4.1.2, 4.4.3

**Comment by SleepyStudents** [comment]
me

**Comment by flaviut** [comment]
I've made some comments on this at https://github.com/gsu-swe-s2019-group-1/project/commit/a128600b5000769bfad3287fd38913f6cd9fb52a, please take a look!
