### ISSUE TITLE
 Implementation- Backend

### ISSUE THREAD

**Issue by anandita-dubey** [gsu-swe-s2019-group-1/project#13]
 **Implement the Database Design (Tables, Backend):**
o Choose the tables related to the two of the major use cases of your system
o Implement the chosen tables using the selected database management system (MySQL, MS-SQL
server, Oracle, etc.)
 Creating tables using SQL scripts makes it easy to create the necessary tables on another
computer: Development Environment, Test Environment, Production Environment;
Deployment
 Note: These are some free hosting database management systems:
- Amazon RDS (Relational Database Service) has a free usage tier for 12 months to
run a Micro DB instance with 20GB of storage and 10 million I/Os
- Google Cloud Firestore / Datastore is document-store with a permanent free tier
of 1GB storage, 50k reads and 20k writes per day.
- MongoDB Atlas has a free tier with a 3-node replica set and 512MB storage.
- Redis Labs offers a 30MB Redis instance for free.
- Heroku Postgres has a free tier limited to 10k individual rows of data.
Note: These are some Web Based Frameworks and IDE tools:
Backend frameworks
 Spring (Java)
 ASP.NET (C#)
 Django (Python)
 Laravel (PHP)
 Express (Node.js)
 Ruby on rails

Frontend Javascript Frameworks
 Angular (Java Script, by
Google)
 React
 Vue
 Ember
 Backbone
Integrated Development
Environment (IDE) Software
 Visual Studio
 IntelliJ IDEA
 Xcode
 Eclipse
 WebStorm
 PhpStorm
 NetBeans
 AWS Cloud9

**Comment by flaviut** [comment]
Backend skeleton has been autogenerated in https://github.com/gsu-swe-s2019-group-1/project/tree/master/backend. All methods that return `HttpStatus.NOT_IMPLEMENTED` need to be implemented to transfer data to/from the database.

**Comment by flaviut** [comment]
Interactive API documentation explaining what everything does can be found at https://avocado-toast.wp6.pw/apidoc/
