### ISSUE TITLE
 Implementation- Frontend

### ISSUE THREAD

**Issue by anandita-dubey** [gsu-swe-s2019-group-1/project#14]
**Implement the Class Diagram Design (Frontend and Logic): (develop/write code)**
 Get an overview of the software frameworks or platforms, programming languages, host, etc.
 Install the necessary Software
 Start creating the main parts (two of the major use cases) for your application (both Frontend, logic
(CODE), and GUI).
 Create a good structure for your code.
 Test that you are able to communicate with the Database (data go from Frontend [GUI] to Backend
[Tables]).
 A description of how to compile and run your code
 You should not instruct us to compile and execute your code in any particular IDE.
 We recommend writing your own build script or generating one in an IDE (ant, mvn, etc.).
 Or, if you chose to host your system in the cloud, make sure to provide the host link, user name and
password in the section of “description for how to compile your code”

**Comment by flaviut** [comment]
I'm planning on doing this in react/typescript since I'm super familiar with that.

**Comment by anandita-dubey** [comment]
I’m good with anything. Alex is working on backend so if you could let him know about it , so that you both could be on same page and he can start working accordingly.

**Comment by flaviut** [comment]
Frontend is done, minus any bugs that may be found from here on. It can be tried out at https://avocado-toast.wp6.pw/

**Comment by anandita-dubey** [comment]
She asked to show her how the program is running during her office hours. For the report, I think I might need just the screenshots !
