### ISSUE TITLE
 System Modeling (Analysis)-Behavioral modeling (Dynamic Modeling):

### ISSUE THREAD

**Issue by anandita-dubey** [gsu-swe-s2019-group-1/project#17]
**2. Behavioral modeling (Dynamic Modeling):**
Using MS Visio, create a UML sequence diagram to illustrating in more details two of the major use cases of your
system. One of those two must correspond to the creation of your system. Show appropriate lifelines, activations,
and message types. You may also use loop, alternative (alt), and optional fragments if needed. You may use your
class diagram to identify the objects’ names and messages (methods) that you need to develop your sequence
diagram.
Important Note:
 A sequence diagram is a visual representation of how objects in a system interact. Keep in mind that
the reasons to create a sequence diagram is to:
 refine your use case diagram and uses cases (adding missed cases [functionalities]),
 refine your class diagram (adding missed methods [messages]),
 transition from the conceptual model and start thinking about the implementation, which is the most
importantly.

**Comment by Cdele** [comment]
![visio](https://user-images.githubusercontent.com/47041050/53690724-2cc6bf00-3d3e-11e9-815b-aa97ee9111e6.jpg)
