### ISSUE TITLE
Write high-level user requirements (#5)

### ISSUE THREAD

**Issue by flaviut** [gsu-swe-s2019-group-1/project#2]
Edit https://github.com/gsu-swe-s2019-group-1/project/blob/master/assignments/asn1/problem_statement.md to include this information.

-------------------
# Problem Statement

 (Overall Project Description, user requirements)

- First, read Ch4 page 88-90.
- What is your product, on a high level?
- Whom is it for?
- What problem does it solve?
- What alternatives are available?
- Why is this project compelling and worth developing?
- Describe the top-level objectives, differentiators, target customers, and
  scope your product.
- What are the competitors and what is novel in your approach?
- Make it clear that the system can be built, making good use of the available
  resources and technology.
- What is interesting about this project from a technical point of view?

**Comment by flaviut** [comment]
This would be a good issue to split between people--it's pretty long.

**Comment by anandita-dubey** [comment]
Okay I shall start doing the first 5 questions! 
The next person who’s willing to do this issue can do the remaining.

**Comment by nessico** [comment]
I can do the remaining

**Comment by flaviut** [comment]
@demo123git 

Looks good! I took your file and converted it to plain text, since that works better with git. This was done in 7828a5985ebfcd3247a2fd80b67e66c2122c70f3.

I've made some revisions in 2d13c781c88d33c23fb230d3f90d76a2e5a6a0de in order rephrase some stuff--my goal is that when the document is put together, it is impossible to tell that more than one person worked on it.

Please let me know if you're unhappy with any of the revisions, I'd be happy to change them!

**Comment by flaviut** [comment]
Finished in 93204de.
