### ISSUE TITLE
Task 4: System Modeling(Analysis)

### ISSUE THREAD

**Issue by Cdele** [gsu-swe-s2019-group-1/project#21]
1.Architecture modeling:
o Use the 4+1 to develop your architectural design(see the slides for more details).
o Use MS Visio to draw the 4+1 views.
2.Behavioral modeling(Dynamic Modeling):
o Using MS Visio, create a UML sequence diagram to illustrate in more details another two use cases of your system. One of those two must correspond to the two use cases you chose in A3.
Note:
o Show appropriate lifelines, activations, and message types.
o You may also use loop, alternative (alt), and optional fragments if needed. 
o You may use your class diagram to identify the objects’ names and messages(methods)that you need to develop your sequence diagram.
Strictly follow the UML standard for Sequence Diagram 
Important Note: A sequence diagram is a visual representation of how objects in a system interact. 
Keep in mind that the reasons to create a sequence diagram is to: 
1.refine your use case diagram and uses cases
(adding missed cases [functionalities]), 
2.refine your class diagram(adding missed methods [messages]), 
3.transition from the conceptual model and start thinking about the implementation, which is the most importantly

**Comment by flaviut** [comment]
Class diagram is auto-generated in https://raw.githubusercontent.com/gsu-swe-s2019-group-1/project/master/assignments/asn4/classdiagram.png
