### ISSUE TITLE
Task 4: Design Measures and Patterns

### ISSUE THREAD

**Issue by flaviut** [gsu-swe-s2019-group-1/project#25]
> - Measure your class diagram coupling and cohesion.
> - What design pattern/s would you choose for your system.
> - Revise your class diagram based on the chosen pattern
> - Using MS Visio, create your chosen design pattern

We use the singleton pattern to connect to the database. Take a look at `backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java`

**Comment by anandita-dubey** [comment]
Hey @flaviut Do you want me to use the auto generated class diagram( by GitHub) to measure the coupling and cohesion or we should use the one we have been submitting in the report so far. Please suggest. I have attached the one we have used in our reports. 
![5859DA95-AFAE-45F0-9009-1FEF7DD318FB](https://user-images.githubusercontent.com/22835631/56054375-a6ca6a80-5d24-11e9-8ac2-520adf043423.png)

**Comment by flaviut** [comment]
I'm not sure what you're asking, github definitely does not generate class diagrams.

The I would update the diagram you attached to reflect the actual class structure (in backend/src/main/java/pw/wp6/avocado_toast), as well as to reflect the 1-1, 1-n relationships (she emphasized that part heavily for the test, so I'd expect that she wants it for the assignment as well).

Fri Apr 12 13:13:28 EDT 2019 demo123git <notifications@github.com>:

**Comment by anandita-dubey** [comment]
Okay! So the one I’ve attached, does it include everything that you’re implementing or is there anything else that has been added so far (so that I can update our class diagram )

**Comment by flaviut** [comment]
I've updated my the class diagram in https://raw.githubusercontent.com/gsu-swe-s2019-group-1/project/master/assignments/asn5/classes.png with the actual classes in the project, as well as some manual adjustments to make the relationships more obvious.

This UML diagram was generated automatically, so it reflects the exact & most up to date structure of the classes.

**Comment by anandita-dubey** [comment]
Thank you !

**Comment by anandita-dubey** [comment]
Hey @flaviut , the class diagram that you’ve updated above, by updating it you mean, after all the changes that happened after the design you guys have used to improve to system, right ?

**Comment by flaviut** [comment]
Yes. It reflects the current class structure.
