### ISSUE TITLE
Complete section 3, "Teamwork Basics"

### ISSUE THREAD

**Issue by flaviut** [gsu-swe-s2019-group-1/project#3]
Edit https://github.com/gsu-swe-s2019-group-1/project/blob/master/assignments/asn1/teamwork_basics.md to include this information.

**Comment by Cdele** [comment]
[
[TeamWork Basics.docx](https://github.com/gsu-swe-s2019-group-1/project/files/2818894/TeamWork.Basics.docx)
](url)

**Comment by flaviut** [comment]
The advantage of keeping files in git is that it is easy to track changes made by multiple people, and that is not possible when files are uploaded as attachments to issues.

When working with git, it's also generally accepted to prefer plain-text files over things like Word documents, since plain text documents make it possible to see what changes between revisions.
