### ISSUE TITLE
Gather team description

### ISSUE THREAD

**Issue by flaviut** [gsu-swe-s2019-group-1/project#6]
Team Description: a table showing the group name, members and their assigned roll and the
group coordinator.

To develop your team capabilities & assignment:

- each team member will write a brief resume emphasizing
  - computer science education,
  - a computing skills inventory (languages, hardware, packages),
- experience in any kind of work

Please reply to this issue with the above information.

**Comment by flaviut** [comment]
## Classes taken

- Data structures
- Computer organization
- System-level programming
- Programming language concepts
- Computer architecture
- Parallel & distributed programming

## Technologies
- Languages: JavaScript, HTML, Java, Scala, CSS, C, Bash, SQL, Nim
- Libraries: Backbone.js, Underscore.js, React, Django, PCRE
- Other: Git, PTC Integrity, RST, SOAP, LATEX, Bugzilla, Wercker, Gitlab CI, Docker

## Experience

At my previous job I worked on doing web development on embedded systems, and worked on basically everything, [from the front-end code](https://www.micromeritics.com/Repository/Files/Envelope-Density-Report.jpg) to the analysis code & system admin stuff for the [Geopyc 1365](https://www.youtube.com/watch?v=TdUiYWuejVI). I worked in Python on the backend, and Javascript/Typescript/Backbone/React on the frontend.

My current job is doing devops, as well as a bit of embedded programming, for GTRI. I've mostly been using Python, as well as a decent amount of bash & C++.

**Comment by nessico** [comment]
### Classes Taken

- Data Structures
- System-level Programming
- Math Models

### Technologies
- Languages: Java, C, Python

### Experience
None

**Comment by anandita-dubey** [comment]
**Courses Taken**
• Data structures
• Computational Intelligence 
• Mobile App Development 
• Intro to Machine Learning 
• Operating System 

**Technologies**
Language- Java 
Skills- Android Studio, Neural Networks 

**Experience**
None

**Comment by Cdele** [comment]
### **Courses Taken**
- Data Structures
- Computer Architecture
- System Level
- Programming language concepts

### **Technologies**
Language- Java,C,Assembly,HTML,CSS

### **Experience**
None

**Comment by apetros1** [comment]
### **Classes Taken**
- Data Structures
- Computer Organizations
- System-level Programming
- Windowing Systems

### **Technologies**
Languages: Java, C, Bash, SQL

### **Experience**
None
