### ISSUE TITLE
Revise and Refine your System (Improved Problem Statement)

### ISSUE THREAD

**Issue by apetros1** [gsu-swe-s2019-group-1/project#7]
Based on the feedback provided and additional topics covered in class, you are to revise, refine, complete and include your problem statement and user requirements with A2. Therefore, you will write an improved version of the Problem Statement you provided in A1.

**Comment by flaviut** [comment]
@demo123git Is there anything that we need to do here? From what I understand, our report was basically perfect :smile:

**Comment by anandita-dubey** [comment]
yeah. She asked me to add a few points there.
